version: "3.9"

services:
  api:
    build:
      context: ./backend
    container_name: url-shortener-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_BASE_URL: ${APP_BASE_URL}

  web:
    build:
      context: ./frontend
    container_name: url-shortener-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_TARGET: http://api:8080
    depends_on:
      - api